"""Schema drift: metadata and migrations must agree; a change without a migration is reported."""

from __future__ import annotations

from typing import Any

import pytest
from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Column, MetaData, Text, text

from epistrel.core.db import make_sync_engine
from epistrel.core.schema import AUTOGENERATE_OPTS, NAMING_CONVENTION, metadata
from tests.conftest import alembic_config


def _diffs(url: str, target: MetaData) -> list[Any]:
    engine = make_sync_engine(url)
    try:
        with engine.connect() as conn:
            ctx = MigrationContext.configure(conn, opts=dict(AUTOGENERATE_OPTS))
            return list(compare_metadata(ctx, target))
    finally:
        engine.dispose()


def _describe(diffs: list[Any]) -> str:
    """One line per autogenerate diff, always naming the table (and column where there is one)."""
    lines = []
    for diff in diffs:
        entry = diff[0] if isinstance(diff, list) else diff
        kind = entry[0]
        if kind in ("add_table", "remove_table"):
            lines.append(f"{kind}: {entry[1].name}")
        elif kind in ("add_column", "remove_column"):
            lines.append(f"{kind}: {entry[2]}.{entry[3].name}")
        elif kind.startswith("modify_"):
            lines.append(f"{kind}: {entry[2]}.{entry[3]} {entry[-2]!r} -> {entry[-1]!r}")
        else:
            lines.append(f"{kind}: {entry[1:]!r}")
    return "\n".join(lines)


def test_metadata_matches_migrations(pg_url: str) -> None:
    diffs = _diffs(pg_url, metadata)
    assert diffs == [], (
        "Schema drift: epistrel.core.schema differs from the migrated database. "
        "Add an Alembic migration.\n" + _describe(diffs)
    )


def test_alembic_check_passes_on_real_metadata(pg_url: str) -> None:
    command.check(alembic_config(pg_url))  # raises AutogenerateDiffsDetected on drift


def test_added_column_is_reported(pg_url: str) -> None:
    clone = MetaData(naming_convention=NAMING_CONVENTION)
    for table in metadata.tables.values():
        table.to_metadata(clone)
    clone.tables["schema_meta"].append_column(Column("drifted", Text, nullable=True))

    diffs = _diffs(pg_url, clone)

    added = [d for d in diffs if d[0] == "add_column" and d[3].name == "drifted"]
    assert added, f"expected an add_column diff for schema_meta.drifted, got:\n{_describe(diffs)}"
    assert added[0][2] == "schema_meta"


def test_alembic_check_detects_drift(scratch_database: str) -> None:
    """`alembic check` reports a column that exists in the database but not in the metadata."""
    cfg = alembic_config(scratch_database)
    command.upgrade(cfg, "head")
    engine = make_sync_engine(scratch_database, isolation_level="AUTOCOMMIT")
    try:
        with engine.connect() as conn:
            conn.execute(text("ALTER TABLE schema_meta ADD COLUMN drifted text"))
    finally:
        engine.dispose()

    with pytest.raises(AutogenerateDiffsDetected, match="drifted"):
        command.check(cfg)
